In [37]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [38]:
dataset = pd.read_csv('datatas.csv', sep=';')
dataset

no kode barang model tas ukuran   warna     harga   status
0     1          SB  Slingbag  Besar  coklat   90000.0   laris 
1     2          SB  Slingbag  Kecil  cream   100000.0   laris 
2     3          SB  Slingbag  Besar  coklat   90000.0  kurang 
3     4          SB  Slingbag  Kecil  cream    90000.0   kurang
4     5          SB  Slingbag  Kecil  hitam    70000.0   laris 
..  ...         ...       ...    ...     ...       ...      ...
95   96          TB   Totebag  besar  coklat   80000.0   kurang
96   97          TB   Totebag  besar   hitam   65000.0    laris
97   98          TB   Totebag  besar   putih   70000.0    laris
98   99          TB   Totebag  besar   cream   50000.0    laris
99  100          TB   Totebag  besar  coklat   67000.0   kurang

[100 rows x 7 columns]

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
enc = LabelEncoder()

In [41]:
dataset['kode barang'] = enc.fit_transform(dataset['kode barang'].values)
dataset['model tas'] = enc.fit_transform(dataset['model tas'].values)
dataset['ukuran'] = enc.fit_transform(dataset['ukuran'].values)
dataset['warna'] = enc.fit_transform(dataset['warna'].values)
dataset['status'] = enc.fit_transform(dataset['status'].values)

In [42]:
dataset

no  kode barang  model tas  ukuran  warna     harga  status
0     1            1          1       0      0   90000.0       5
1     2            1          1       2      3  100000.0       5
2     3            1          1       0      0   90000.0       3
3     4            1          1       2      3   90000.0       2
4     5            1          1       2      5   70000.0       5
..  ...          ...        ...     ...    ...       ...     ...
95   96            2          2       3      0   80000.0       2
96   97            2          2       3      4   65000.0       4
97   98            2          2       3      6   70000.0       4
98   99            2          2       3      2   50000.0       4
99  100            2          2       3      0   67000.0       2

[100 rows x 7 columns]

In [43]:
atr_dataset = dataset.drop(columns = 'status')
atr_dataset

no  kode barang  model tas  ukuran  warna     harga
0     1            1          1       0      0   90000.0
1     2            1          1       2      3  100000.0
2     3            1          1       0      0   90000.0
3     4            1          1       2      3   90000.0
4     5            1          1       2      5   70000.0
..  ...          ...        ...     ...    ...       ...
95   96            2          2       3      0   80000.0
96   97            2          2       3      4   65000.0
97   98            2          2       3      6   70000.0
98   99            2          2       3      2   50000.0
99  100            2          2       3      0   67000.0

[100 rows x 6 columns]

In [44]:
cls_dataset = dataset['status']
cls_dataset

0     5
1     5
2     3
3     2
4     5
     ..
95    2
96    4
97    4
98    4
99    2
Name: status, Length: 100, dtype: int32

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

In [46]:
xtrain, xtest, ytrain, ytest = train_test_split(atr_dataset, cls_dataset, test_size=0.2, random_state=1)
tree_dataset = DecisionTreeClassifier(random_state=1)
tree_dataset.fit(xtrain, ytrain)

DecisionTreeClassifier(random_state=1)

In [47]:
y_pred = tree_dataset.predict(xtest)
Cm = confusion_matrix(ytest, y_pred)
print("Confusion Matrix")
print(Cm)
akurasi = classification_report(ytest, y_pred)
print("Tingkat Akurasi Algoritma C4,5")
print('Akurasi :', akurasi)
akurasi = accuracy_score(ytest, y_pred)
print("Tingkat Akurasi : %d persen" %(akurasi*100))

Confusion Matrix
[[1 0 4 0]
 [1 2 0 1]
 [4 0 7 0]
 [0 0 0 0]]
Tingkat Akurasi Algoritma C4,5
Akurasi :               precision    recall  f1-score   support

           2       0.17      0.20      0.18         5
           3       1.00      0.50      0.67         4
           4       0.64      0.64      0.64        11
           5       0.00      0.00      0.00         0

    accuracy                           0.50        20
   macro avg       0.45      0.33      0.37        20
weighted avg       0.59      0.50      0.53        20

Tingkat Akurasi : 50 persen


C:\Users\Windyani\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
from sklearn.tree import export_graphviz
export_graphviz(tree_dataset, out_file="Tree_status.dot", class_names=["laris","kurang"],
                feature_names=atr_dataset.columns, impurity=False, filled=True)

IndexError: list index out of range